##################################
# NETWORK & GENERAL
##################################
bind 0.0.0.0
protected-mode no
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300

##################################
# MEMORY MANAGEMENT (Wajib diset)
##################################
# Sesuaikan dengan limit docker-compose (512MB)
# Kita pakai 400MB agar ada sisa untuk overhead
maxmemory 400mb

# STRATEGI PENGHAPUSAN (PENTING UNTUK LARAVEL)
# volatile-lru: Hapus yang ada expire-nya saja (Cache). 
# Data Queue (tanpa expire) aman tidak akan dihapus.
maxmemory-policy volatile-lru

##################################
# PERSISTENCE (RDB - Snapshot)
##################################
# Simpan ke disk jika:
# 1 key berubah dalam 900 detik (15 menit)
# 10 keys berubah dalam 300 detik (5 menit)
# 10000 keys berubah dalam 60 detik (1 menit)
save 900 1
save 300 10
save 60 10000

stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /data

##################################
# PERSISTENCE (AOF - Append Only)
##################################
# Matikan AOF untuk performa maksimal. 
# Nyalakan (yes) jika data queue SANGAT TIDAK BOLEH HILANG (tapi sedikit lebih lambat)
appendonly no 
# appendfsync everysec

##################################
# ADVANCED LATENCY TUNING
##################################
# Mematikan replikasi diskless agar CPU lebih ringan di single instance
repl-diskless-sync no