[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
# Menambahkan --queue=default dan --sleep=3 agar worker lebih responsif 
# dan efisien dalam mengecek antrian Redis.
command=php /app/artisan queue:work --queue=default --sleep=3 --tries=3 --timeout=90
autostart=true
autorestart=true
# Menggunakan root untuk menghindari masalah permission akses file di dalam container
user=root
# Jumlah worker paralel (sesuaikan dengan core CPU jika butuh performa lebih)
numprocs=2
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=3600
stopsignal=SIGTERM