; [Date]
date.timezone = "Asia/Jakarta"

[PHP]
upload_max_filesize = 20M
post_max_size = 20M
; Menaikkan limit memori agar worker tidak mudah restart
memory_limit = 512M
; Menonaktifkan fungsi yang tidak perlu untuk keamanan dan kecepatan
disable_functions = passthru,shell_exec,system

[JIT]
; Mengaktifkan JIT (Just-In-Time) Compiler
opcache.jit_buffer_size=128M
; 1255 adalah mode paling agresif untuk optimasi fungsi dan tracing
opcache.jit=1255

