; [Date]
date.timezone = "Asia/Jakarta"

[PHP]
upload_max_filesize = 20M
post_max_size = 20M
; Menaikkan limit memori agar worker tidak mudah restart
memory_limit = 512M
; Menonaktifkan fungsi yang tidak perlu untuk keamanan dan kecepatan
disable_functions = passthru,shell_exec,system
