; [Date]
date.timezone = "Asia/Jakarta"

[PHP]
; Menaikkan limit memori agar worker tidak mudah restart
memory_limit = 512M
; Menonaktifkan fungsi yang tidak perlu untuk keamanan dan kecepatan
disable_functions = passthru,shell_exec,system

[Opcache]
zend_extension=opcache.so
opcache.enable=1
opcache.enable_cli=1
; Alokasikan RAM besar untuk menyimpan bytecode (naikkan jika project sangat besar)
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
; Jumlah file maksimal yang di-cache
opcache.max_accelerated_files=20000
; JANGAN cek perubahan file (sangat agresif, hemat I/O disk)
; Anda harus restart container jika ada perubahan kode
opcache.validate_timestamps=0
; Optimasi pemanggilan fungsi
opcache.save_comments=0
opcache.fast_shutdown=1

[JIT]
; Mengaktifkan JIT (Just-In-Time) Compiler
opcache.jit_buffer_size=128M
; 1255 adalah mode paling agresif untuk optimasi fungsi dan tracing
opcache.jit=1255

